require: rubocop-performance

inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6.0
  Exclude:
    - db/schema.rb
    - bin/spring
    - config/deploy.rb
    - vendor/**/*
    - bin/*
    - node_modules/**/*

Metrics/BlockLength:
  Exclude:
    - "**/config/**/*.rb"
    - "**/spec/**/*.rb"
    - "**/app/admin/**/*.rb"
    - "**/app/views/**/*.json.jbuilder"

Style/CollectionMethods:
  PreferredMethods:
    find: detect
    reduce: inject
    collect: map
    find_all: select

Bundler/OrderedGems:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Layout/DotPosition:
  EnforcedStyle: leading
