version: '3'
services:
  db:
    env_file: .env
    image: postgres:11.2-alpine
  nginx:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - ./volumes/nginx/html:/usr/share/nginx/html
      - ./volumes/nginx/certs:/etc/nginx/certs:ro
  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - ./volumes/nginx/html:/usr/share/nginx/html
      - ./volumes/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/production/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - /srv/volumes/nginx/conf.d:/etc/nginx/conf.d
      - /srv/volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - /srv/volumes/nginx/html:/usr/share/nginx/html
      - /srv/volumes/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx
  app:
    build:
      context: .
      dockerfile: ./docker/production/app/Dockerfile
    restart: always
    ports:
      - 3000
    environment: &environment
      - RAILS_ENV=production
      - VIRTUAL_HOST=konsultacjeobywatelskie.pl
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=konsultacjeobywatelskie.pl
    volumes: &volumes
      - ./volumes/app/log:/home/app/src/log
      - ./volumes/app/tmp:/home/app/src/tmp

networks:
  default:
    external:
      name: webproxy
