FROM ruby:2.6.3-alpine
ENV RAILS_ENV production
ENV NODE_ENV production
ARG RAILS_MASTER_KEY
RUN apk add --update --no-cache \
      bash \
      build-base \
      nodejs \
      tzdata \
      libxml2-dev \
      libxslt-dev \
      postgresql-dev \
      yarn
RUN bundle config build.nokogiri --use-system-libraries
RUN adduser -D app
USER app
RUN mkdir /home/app/polikompas
WORKDIR /home/app/polikompas
COPY --chown=app:app Gemfile /home/app/polikompas
COPY --chown=app:app Gemfile.lock /home/app/polikompas
RUN bundle install --jobs=$(nproc) --without=development test
COPY --chown=app:app . /home/app/polikompas
RUN yarn install
RUN bin/rails webpacker:compile
CMD rm -f tmp/pids/server.pid && bin/rails s -b 0.0.0.0 -p $PORT
