version: '3'
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=polikompas
      - POSTGRES_PASSWORD=polikompas
      - POSTGRES_DB=polikompas_production
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx-web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/volumes/nginx/conf.d:/etc/nginx/conf.d
      - ~/volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html/public
      - ~/volumes/nginx/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - ~/volumes/nginx/conf.d:/etc/nginx/conf.d
      - ~/volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html/public
      - ~/volumes/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/production/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    depends_on:
      - nginx

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - ~/volumes/nginx/conf.d:/etc/nginx/conf.d
      - ~/volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - ~/volumes/nginx/certs:/etc/nginx/certs:rw
      - nginx-html:/usr/share/nginx/html/public
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx-web
    depends_on:
      - nginx
      - nginx-gen

  app:
    build:
      context: .
      dockerfile: ./docker/production/app/Dockerfile
      args:
        CREDENTIALS_KEY: "${CREDENTIALS_KEY}"
    restart: always
    ports:
      - 3000
    environment: &environment
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - VIRTUAL_HOST=konsultacjeobywatelskie.pl
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=konsultacjeobywatelskie.pl
      - LETSENCRYPT_EMAIL=michal.zajac@gmail.com
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - POSTGRES_USER=polikompas
      - POSTGRES_PASSWORD=polikompas
    volumes: &volumes
      - ./volumes/app/log:/home/app/src/log
      - ./volumes/app/tmp:/home/app/src/tmp
      - nginx-html:/home/app/src/public
    depends_on:
      - nginx
      - nginx-gen
      - nginx-letsencrypt
      - db

volumes:
  db-data:
  nginx-html:

networks:
  default:
    external:
      name: webproxy
