#!/bin/bash

if [[ -a tmp/pids/server.pid ]]; then
  rm -r tmp/pids/server.pid
fi

if [[ $RAILS_ENV == "production" ]]; then
  rm -rf /usr/share/nginx/html/public
  mkdir -p /usr/share/nginx/html/public
  rake webpacker:compile
  cp -rf public/* /usr/share/nginx/html/public
fi

bin/rails server -b 0.0.0.0 -p $PORT
