#!/bin/sh

if [[ -a tmp/pids/server.pid ]]; then
  rm -r tmp/pids/server.pid
fi

if [[ $RAILS_ENV == "production" ]]; then
  rake webpacker:compile
  mkdir -p /usr/share/nginx/html
  cp -R public/* /usr/share/nginx/html/
fi

bin/rails server -b 0.0.0.0 -p $PORT
