default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


docker-compose: &docker-compose
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { "5432" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>

development:
  <<: *default
  <<: *docker-compose
  database: <%= ENV.fetch("POSTGRES_DB") { "polikompas_development" } %>

test:
  <<: *default
  <<: *docker-compose
  database: <%= ENV.fetch("POSTGRES_DB") { "polikompas_test" } %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql://localhost:5432/polikompas_production" } %>
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
